# Generated by Django 4.2.4 on 2023-08-23 17:41

from django.db import migrations, models

import wormhole.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(choices=[("staff", "Staff"), ("user", "User")], default="staff", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=wormhole.utils.models._generate_medium_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
