---
apiVersion: v2
description: wormhole Helm Chart
name: wormhole
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: Leeward Bound
    email: leeward@boundcorp.net
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: "12.1.13"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
