# Generated by Django 4.2.4 on 2023-08-23 18:09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wormhole.utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=wormhole.utils.models._generate_medium_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("contract_address", models.CharField(max_length=42)),
                ("from_tx_hash", models.CharField(max_length=66)),
                ("block_number", models.PositiveIntegerField()),
                ("block_timestamp", models.DateTimeField()),
                ("proposal_id", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("proposer", models.CharField(max_length=42)),
                ("start_block", models.PositiveIntegerField()),
                ("end_block", models.PositiveIntegerField()),
                ("original_event_data", models.JSONField()),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProposalVote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("from_tx_hash", models.CharField(max_length=66)),
                ("block_number", models.PositiveIntegerField()),
                ("block_timestamp", models.DateTimeField()),
                ("reason", models.TextField()),
                ("support", models.IntegerField()),
                ("voter", models.CharField(max_length=42)),
                ("votes", models.PositiveIntegerField()),
                ("original_event_data", models.JSONField()),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="indexer.proposal"
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
                "abstract": False,
            },
        ),
    ]
