# Generated by Django 4.2.4 on 2023-08-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="contract_address",
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="end_block",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposer",
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="start_block",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="proposalvote",
            name="support",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="proposalvote",
            name="voter",
            field=models.CharField(db_index=True, max_length=42),
        ),
    ]
